### ISSUE TITLE
Selection of far field ground motions only with more than one GMPE.

### ISSUE THREAD

**Issue by zeeshanbhat1** [elisa82/haselREC#2]
Dear Team,

I am using this code for ground motion selection. The code is quite helpful for openquake users. I have some doubts regarding the selection of ground motions.
1. How can we input more than one GMPE for selection of ground motions.
2. Is there a way to define a distance range. So as to avoid the selection of near field ground motions.
3. There is significant difference in matching between the CMS computed and the mean of selected ground. The file is attached here. [https://iitracin-my.sharepoint.com/:b:/g/personal/zbhat_eq_iitr_ac_in/ERKNmiLxr6JImG3gWD4_9wIB33U5IO3e8SBJS-r5FCKyww?e=7zAhd3].
Any Suggestions will be highly appreciable.

Regards,
Zeeshan Bhat

**Comment by elisa82** [comment]
Dear Zeeshan,
 thank you for using haselREC. You're feedback is much appreciated. Here the answers to your questions:
1) at the moment haselREC is able to use only one GMPE to compute the CS;
2) Yes, you can define the distance range in the .ini file using rjb_range=[rmin,rmax]. You can define rmin and rmax in km so as to avoid the selection of near field ground motions;
3) Sorry, I am not able to see the figure. Can you also give me additional details in order to understand the difference? i.e. how did you computed the mean? Did you considered RotD50 recordings? Which database have you considered? Thank you

**Comment by zeeshanbhat1** [comment]
Dear Elisa,
 Thank you for your suggestions.
1. I tried to define the "rjb_range" command in the .ini file but the ground motion data are still coming the same.
2. I am using NGA Database. the mean is computed using the already implemented procedure in code. The result are not matching well as shown in the attached file. https://iitracin-my.sharepoint.com/:u:/g/personal/zbhat_eq_iitr_ac_in/EdQRh8ejQ1FOracMuI_01CwBRGEon4N7Ezpq0b8M_yG2Dg?e=y2gW9o[](url)

Regards,
Zeeshan Bhat

**Comment by elisa82** [comment]
Dear Zeeshan,

 1. You are right. That option was not enabled yet. I've upgraded the code and now it works. The distance is still defined based on radius_dist. However, if the minimum and maximum distances thus obtained are lower or higher (respectively) than those defined in dist_range, they are fixed accordingly. The option is called dist_range.
 
 2. I was able to check your files. The selection is not good but it depends on the parameters set by you. Try to increase the number of recordings for example or use the complete database. At the moment you are using demo/Flatfile-NGA-West2-Reduced.csv. This is a reduced database that I've prepared for the demos in order to make the run fast. The complete database is included in GM-Records/database_flatfile.csv. 
 
 Hope this helps
Elisa

**Comment by zeeshanbhat1** [comment]
Dear Elisa,

Thank you for your suggestions. The code is now running quite well with good matching as well. However it is showing an error in one of the realization file. Could you please help me in sorting out this error. The file is attached below. [https://iitracin-my.sharepoint.com/:u:/g/personal/zbhat_eq_iitr_ac_in/EQWO1SeRNk9EhFwrbxoBMJYBvMxdVIcoLE6DcoUQ9fwszg?e=RD9lnF](url)
Regards,
Zeeshan Bhat

**Comment by elisa82** [comment]
Sorry, I am not able to open the link

**Comment by zeeshanbhat1** [comment]
Sorry, The link is attached below.
https://iitracin-my.sharepoint.com/:u:/g/personal/zbhat_eq_iitr_ac_in/EQWO1SeRNk9EhFwrbxoBMJYBvMxdVIcoLE6DcoUQ9fwszg?e=cEdbyt[](url)

**Comment by elisa82** [comment]
The probability of exceedance in wrong: "probability_of_exceedance={0.00001}"
Are you sure you have defined this poe (0.00001) in OpenQuake?
Best regards
Elisa

**Comment by zeeshanbhat1** [comment]
Dear Elisa,

Yes, I have defined "0.00001" in openquake. Even that is also evident from the "hazard map mean file" The job file of openquake is attached below.``https://iitracin-my.sharepoint.com/:u:/g/personal/zbhat_eq_iitr_ac_in/EVzHdkegrMdJqDfEXe9QGP8BIFSSqnapnqaf2xfx1qTwXw?e=2w94Ep [](url)

**Comment by elisa82** [comment]
Ok, the problem is that "SA-0.00001" is not found in the hazard map mean file because it is written as SA(0.1)-1e-05 rather than SA-0.00001.
I have to fix this. Thank you for having raised this issue.
I will let you know as soon as I will have fixed the issue
Thanks
Best regards
Elisa

**Comment by elisa82** [comment]
Fixed. Please let me know if you encounter other issues. User's testing is very important.
Thanks
best regards
Elisa

**Comment by zeeshanbhat1** [comment]
Dear Elisa,

I tested the updated code. Now it is showing error even at "0.0001". I guess there is some issue with the  format of "poe" again. Because it is showing "Key Error as SA(1.0) 1e-04" instead of "SA(1.0) 0.0001". The file is attached here. https://iitracin-my.sharepoint.com/:u:/g/personal/zbhat_eq_iitr_ac_in/EfqrwYZC5P1Ii8TNYt13NroB4MUcIzMbO36gRCxEGd9uIw?e=iWcRmf[](url)

Regards,
Zeeshan

**Comment by zeeshanbhat1** [comment]
Dear Elisa,

Any Update.

**Comment by elisa82** [comment]
Please try now
