### ISSUE TITLE
Error in Scale factor

### ISSUE THREAD

**Issue by zeeshanbhat** [elisa82/haselREC#3]
Dear Team,

My job file is running well at SA(1.0). However when I change the intensity measure to SA(1.5). It is showing an error "valueerror: setting an array element with a sequence". I didn't change anything in the job file except the intensity measure. I could not resolve this error. Any suggestions will be appreciated.
https://iitracin-my.sharepoint.com/:u:/g/personal/zbhat_eq_iitr_ac_in/ET-0CUC28RJJrXC-pFmUGuoB6bb-QDI-N_EieuhN0Xv3vw?e=WzwqYY[](url)

Regards,
Zeeshan Bhat

**Comment by zeeshanbhat** [comment]
Dear Team,

Gentle Reminder.

Regards,
Zeeshan

**Comment by zeeshanbhat** [comment]
Dear Elisa,

I have included the realization file of both SA(1.0) and SA(1.5). The code shows the error only in case of SA(1.5). Any Suggestions will be appreciated. https://iitracin-my.sharepoint.com/:u:/g/personal/zbhat_eq_iitr_ac_in/ESWeA1PTdM1EvjBYYr1P0NYBhoFWvaN0mDOONnb8A_dnLw?e=MEqRaa[](url).
If there is any error from my side. Please let me know so that I can correct it. Eagerly waiting for your reply

Regards,
Zeeshan

**Comment by elisa82** [comment]
Dear Zeeshan, 
 the problem is that you are using a target period (1.5 s) for which the response spectra included in the database are not defined. Please have a look at the database flatfile:

rotD50_pga;rotD50_T0_010;rotD50_T0_025;rotD50_T0_040;rotD50_T0_050;rotD50_T0_070;rotD50_T0_100;rotD50_T0_150;rotD50_T0_200;rotD50_T0_250;rotD50_T0_300;rotD50_T0_350;rotD50_T0_400;rotD50_T0_450;rotD50_T0_500;rotD50_T0_600;rotD50_T0_700;rotD50_T0_750;rotD50_T0_800;rotD50_T0_900;rotD50_T1_000;rotD50_T1_200;**rotD50_T1_400;rotD50_T1_600**;rotD50_T1_800;rotD50_T2_000;rotD50_T2_500;rotD50_T3_000;rotD50_T3_500;rotD50_T4_000;rotD50_T5_000;rotD50_T6_000;rotD50_T7_000;rotD50_T8_000;rotD50_T9_000;rotD50_T10_000

So you can't use the target period of 1.5 s. If you really need that period, one idea may be to interpolate the recorded response spectra and add a new column (rotD50_T1_500) to the database flatfile. Please note that you will have also to change the code in order to read the additional column.

Regards
Elisa
